packages:
  - "packages/*"
  - "apps/*"

allowBuilds:
  esbuild: true
  sharp: true
  "@parcel/watcher": true
  "@tailwindcss/oxide": true

minimumReleaseAgeExclude:
  - oxlint-plugin-react-doctor@0.9.14
  - react-doctor@0.9.14
