/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthenticatedRouteRouteImport } from './routes/_unauthenticated/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnauthenticatedSignUpRouteRouteImport } from './routes/_unauthenticated/sign-up/route'
import { Route as UnauthenticatedSignInRouteRouteImport } from './routes/_unauthenticated/sign-in/route'
import { Route as AuthenticatedRecipesRouteRouteImport } from './routes/_authenticated/recipes/route'
import { Route as AuthenticatedProfileRouteRouteImport } from './routes/_authenticated/profile/route'
import { Route as AuthenticatedHomeRouteRouteImport } from './routes/_authenticated/home/route'
import { Route as AuthenticatedRecipes_formRouteRouteImport } from './routes/_authenticated/recipes_/_form/route'
import { Route as AuthenticatedRecipesRecipeIdRouteRouteImport } from './routes/_authenticated/recipes_/$recipeId/route'
import { Route as AuthenticatedRecipes_formNewRouteRouteImport } from './routes/_authenticated/recipes_/_form/new/route'
import { Route as AuthenticatedRecipes_formRecipeIdEditRouteRouteImport } from './routes/_authenticated/recipes_/_form/$recipeId_/edit/route'

const AuthenticatedRecipesRouteImport = createFileRoute(
  '/_authenticated/recipes_',
)()

const UnauthenticatedRouteRoute = UnauthenticatedRouteRouteImport.update({
  id: '/_unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRecipesRoute = AuthenticatedRecipesRouteImport.update({
  id: '/recipes_',
  path: '/recipes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const UnauthenticatedSignUpRouteRoute =
  UnauthenticatedSignUpRouteRouteImport.update({
    id: '/sign-up',
    path: '/sign-up',
    getParentRoute: () => UnauthenticatedRouteRoute,
  } as any)
const UnauthenticatedSignInRouteRoute =
  UnauthenticatedSignInRouteRouteImport.update({
    id: '/sign-in',
    path: '/sign-in',
    getParentRoute: () => UnauthenticatedRouteRoute,
  } as any)
const AuthenticatedRecipesRouteRoute =
  AuthenticatedRecipesRouteRouteImport.update({
    id: '/recipes',
    path: '/recipes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRouteRoute =
  AuthenticatedProfileRouteRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHomeRouteRoute = AuthenticatedHomeRouteRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecipes_formRouteRoute =
  AuthenticatedRecipes_formRouteRouteImport.update({
    id: '/_form',
    getParentRoute: () => AuthenticatedRecipesRoute,
  } as any)
const AuthenticatedRecipesRecipeIdRouteRoute =
  AuthenticatedRecipesRecipeIdRouteRouteImport.update({
    id: '/recipes_/$recipeId',
    path: '/recipes/$recipeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecipes_formNewRouteRoute =
  AuthenticatedRecipes_formNewRouteRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedRecipes_formRouteRoute,
  } as any)
const AuthenticatedRecipes_formRecipeIdEditRouteRoute =
  AuthenticatedRecipes_formRecipeIdEditRouteRouteImport.update({
    id: '/$recipeId_/edit',
    path: '/$recipeId/edit',
    getParentRoute: () => AuthenticatedRecipes_formRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof AuthenticatedHomeRouteRoute
  '/profile': typeof AuthenticatedProfileRouteRoute
  '/recipes': typeof AuthenticatedRecipes_formRouteRouteWithChildren
  '/sign-in': typeof UnauthenticatedSignInRouteRoute
  '/sign-up': typeof UnauthenticatedSignUpRouteRoute
  '/recipes/$recipeId': typeof AuthenticatedRecipesRecipeIdRouteRoute
  '/recipes/new': typeof AuthenticatedRecipes_formNewRouteRoute
  '/recipes/$recipeId/edit': typeof AuthenticatedRecipes_formRecipeIdEditRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof AuthenticatedHomeRouteRoute
  '/profile': typeof AuthenticatedProfileRouteRoute
  '/recipes': typeof AuthenticatedRecipes_formRouteRouteWithChildren
  '/sign-in': typeof UnauthenticatedSignInRouteRoute
  '/sign-up': typeof UnauthenticatedSignUpRouteRoute
  '/recipes/$recipeId': typeof AuthenticatedRecipesRecipeIdRouteRoute
  '/recipes/new': typeof AuthenticatedRecipes_formNewRouteRoute
  '/recipes/$recipeId/edit': typeof AuthenticatedRecipes_formRecipeIdEditRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_unauthenticated': typeof UnauthenticatedRouteRouteWithChildren
  '/_authenticated/home': typeof AuthenticatedHomeRouteRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRouteRoute
  '/_authenticated/recipes': typeof AuthenticatedRecipesRouteRoute
  '/_unauthenticated/sign-in': typeof UnauthenticatedSignInRouteRoute
  '/_unauthenticated/sign-up': typeof UnauthenticatedSignUpRouteRoute
  '/_authenticated/recipes_/$recipeId': typeof AuthenticatedRecipesRecipeIdRouteRoute
  '/_authenticated/recipes_': typeof AuthenticatedRecipesRouteWithChildren
  '/_authenticated/recipes_/_form': typeof AuthenticatedRecipes_formRouteRouteWithChildren
  '/_authenticated/recipes_/_form/new': typeof AuthenticatedRecipes_formNewRouteRoute
  '/_authenticated/recipes_/_form/$recipeId_/edit': typeof AuthenticatedRecipes_formRecipeIdEditRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/profile'
    | '/recipes'
    | '/sign-in'
    | '/sign-up'
    | '/recipes/$recipeId'
    | '/recipes/new'
    | '/recipes/$recipeId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/profile'
    | '/recipes'
    | '/sign-in'
    | '/sign-up'
    | '/recipes/$recipeId'
    | '/recipes/new'
    | '/recipes/$recipeId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_unauthenticated'
    | '/_authenticated/home'
    | '/_authenticated/profile'
    | '/_authenticated/recipes'
    | '/_unauthenticated/sign-in'
    | '/_unauthenticated/sign-up'
    | '/_authenticated/recipes_/$recipeId'
    | '/_authenticated/recipes_'
    | '/_authenticated/recipes_/_form'
    | '/_authenticated/recipes_/_form/new'
    | '/_authenticated/recipes_/_form/$recipeId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  UnauthenticatedRouteRoute: typeof UnauthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_unauthenticated': {
      id: '/_unauthenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UnauthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/recipes_': {
      id: '/_authenticated/recipes_'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof AuthenticatedRecipesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_unauthenticated/sign-up': {
      id: '/_unauthenticated/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof UnauthenticatedSignUpRouteRouteImport
      parentRoute: typeof UnauthenticatedRouteRoute
    }
    '/_unauthenticated/sign-in': {
      id: '/_unauthenticated/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof UnauthenticatedSignInRouteRouteImport
      parentRoute: typeof UnauthenticatedRouteRoute
    }
    '/_authenticated/recipes': {
      id: '/_authenticated/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof AuthenticatedRecipesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recipes_/_form': {
      id: '/_authenticated/recipes_/_form'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof AuthenticatedRecipes_formRouteRouteImport
      parentRoute: typeof AuthenticatedRecipesRoute
    }
    '/_authenticated/recipes_/$recipeId': {
      id: '/_authenticated/recipes_/$recipeId'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId'
      preLoaderRoute: typeof AuthenticatedRecipesRecipeIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recipes_/_form/new': {
      id: '/_authenticated/recipes_/_form/new'
      path: '/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof AuthenticatedRecipes_formNewRouteRouteImport
      parentRoute: typeof AuthenticatedRecipes_formRouteRoute
    }
    '/_authenticated/recipes_/_form/$recipeId_/edit': {
      id: '/_authenticated/recipes_/_form/$recipeId_/edit'
      path: '/$recipeId/edit'
      fullPath: '/recipes/$recipeId/edit'
      preLoaderRoute: typeof AuthenticatedRecipes_formRecipeIdEditRouteRouteImport
      parentRoute: typeof AuthenticatedRecipes_formRouteRoute
    }
  }
}

interface AuthenticatedRecipes_formRouteRouteChildren {
  AuthenticatedRecipes_formNewRouteRoute: typeof AuthenticatedRecipes_formNewRouteRoute
  AuthenticatedRecipes_formRecipeIdEditRouteRoute: typeof AuthenticatedRecipes_formRecipeIdEditRouteRoute
}

const AuthenticatedRecipes_formRouteRouteChildren: AuthenticatedRecipes_formRouteRouteChildren =
  {
    AuthenticatedRecipes_formNewRouteRoute:
      AuthenticatedRecipes_formNewRouteRoute,
    AuthenticatedRecipes_formRecipeIdEditRouteRoute:
      AuthenticatedRecipes_formRecipeIdEditRouteRoute,
  }

const AuthenticatedRecipes_formRouteRouteWithChildren =
  AuthenticatedRecipes_formRouteRoute._addFileChildren(
    AuthenticatedRecipes_formRouteRouteChildren,
  )

interface AuthenticatedRecipesRouteChildren {
  AuthenticatedRecipes_formRouteRoute: typeof AuthenticatedRecipes_formRouteRouteWithChildren
}

const AuthenticatedRecipesRouteChildren: AuthenticatedRecipesRouteChildren = {
  AuthenticatedRecipes_formRouteRoute:
    AuthenticatedRecipes_formRouteRouteWithChildren,
}

const AuthenticatedRecipesRouteWithChildren =
  AuthenticatedRecipesRoute._addFileChildren(AuthenticatedRecipesRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHomeRouteRoute: typeof AuthenticatedHomeRouteRoute
  AuthenticatedProfileRouteRoute: typeof AuthenticatedProfileRouteRoute
  AuthenticatedRecipesRouteRoute: typeof AuthenticatedRecipesRouteRoute
  AuthenticatedRecipesRecipeIdRouteRoute: typeof AuthenticatedRecipesRecipeIdRouteRoute
  AuthenticatedRecipesRoute: typeof AuthenticatedRecipesRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHomeRouteRoute: AuthenticatedHomeRouteRoute,
  AuthenticatedProfileRouteRoute: AuthenticatedProfileRouteRoute,
  AuthenticatedRecipesRouteRoute: AuthenticatedRecipesRouteRoute,
  AuthenticatedRecipesRecipeIdRouteRoute:
    AuthenticatedRecipesRecipeIdRouteRoute,
  AuthenticatedRecipesRoute: AuthenticatedRecipesRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface UnauthenticatedRouteRouteChildren {
  UnauthenticatedSignInRouteRoute: typeof UnauthenticatedSignInRouteRoute
  UnauthenticatedSignUpRouteRoute: typeof UnauthenticatedSignUpRouteRoute
}

const UnauthenticatedRouteRouteChildren: UnauthenticatedRouteRouteChildren = {
  UnauthenticatedSignInRouteRoute: UnauthenticatedSignInRouteRoute,
  UnauthenticatedSignUpRouteRoute: UnauthenticatedSignUpRouteRoute,
}

const UnauthenticatedRouteRouteWithChildren =
  UnauthenticatedRouteRoute._addFileChildren(UnauthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  UnauthenticatedRouteRoute: UnauthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
