/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VariantIdRouteRouteImport } from './routes/$variantId/route'
import { Route as CompareRouteRouteImport } from './routes/compare/route'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VariantIdRouteRoute = VariantIdRouteRouteImport.update({
  id: '/$variantId',
  path: '/$variantId',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRouteRoute = CompareRouteRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$variantId': typeof VariantIdRouteRoute
  '/compare': typeof CompareRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$variantId': typeof VariantIdRouteRoute
  '/compare': typeof CompareRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$variantId': typeof VariantIdRouteRoute
  '/compare': typeof CompareRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$variantId' | '/compare'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$variantId' | '/compare'
  id: '__root__' | '/' | '/$variantId' | '/compare'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VariantIdRouteRoute: typeof VariantIdRouteRoute
  CompareRouteRoute: typeof CompareRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$variantId': {
      id: '/$variantId'
      path: '/$variantId'
      fullPath: '/$variantId'
      preLoaderRoute: typeof VariantIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VariantIdRouteRoute: VariantIdRouteRoute,
  CompareRouteRoute: CompareRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
